#!/usr/bin/env bash
# title					:Enhanced BASH v3
# description			:
# author				:Jessica Brown
# date					:2022-04-21
# version				:3.0.0
# usage					:
# notes					:
# bash_version	:5.1.16(1)-release
# ==============================================================================

export eb3_BinPath=${scriptLocation}$(config_get dirSeparator)$(config_get eb3BinPath)$(config_get dirSeparator)
export eb3_CachePath=${eb3_BinPath}$(config_get eb3CachePath)$(config_get dirSeparator)
export eb3_TempPath=${eb3_CachePath}$(config_get eb3TempPath)$(config_get dirSeparator)
export eb3_LibPath=${eb3_BinPath}$(config_get eb3LibPath)$(config_get dirSeparator)
export eb3_ModPath=${eb3_BinPath}$(config_get eb3ModPath)$(config_get dirSeparator)
export eb3_EtcPath=${scriptLocation}$(config_get dirSeparator)$(config_get eb3EtcPath)$(config_get dirSeparator)
export eb3_ConfPath=${eb3_EtcPath}$(config_get eb3ConfPath)$(config_get dirSeparator)
export eb3_OptPath=${eb3_EtcPath}$(config_get eb3OptPath)$(config_get dirSeparator)
export eb3_UsrPath=${scriptLocation}$(config_get dirSeparator)$(config_get eb3UsrPath)$(config_get dirSeparator)
export eb3_OverRidesPath=${eb3_UsrPath}$(config_get eb3OverRidePath)$(config_get dirSeparator)
export eb3_ThemesPath=${eb3_UsrPath}$(config_get eb3ThemesPath)$(config_get dirSeparator)
export eb3_VarPath=${scriptLocation}$(config_get dirSeparator)$(config_get eb3VarPath)$(config_get dirSeparator)
export eb3_LogsPath=${eb3_VarPath}$(config_get eb3LogsPath)$(config_get dirSeparator)
export eb3_DirJumpPath=${eb3_VarPath}$(config_get eb3DirJumpPath)$(config_get dirSeparator)
export eb3_BackupPath=${eb3_VarPath}$(config_get eb3BackupPath)$(config_get dirSeparator)
export eb3_LogsPath=${eb3_VarPath}$(config_get eb3LogsPath)$(config_get dirSeparator)
export eb3_systemFolders=("${eb3_BinPath}" "${eb3_CachePath}" "${eb3_TempPath}" "${eb3_LibPath}" "${eb3_ModPath}" "${eb3_EtcPath}" "${eb3_ConfPath}" "${eb3_OptPath}" "${eb3_UsrPath}" "${eb3_ThemesPath}" "${eb3_VarPath}" "${eb3_LogsPath}" "${eb3_OverRidesPath}" "${eb3_DirJumpPath}" "${eb3_BackupPath}" "${eb3_LogsPath}")