#!/usr/bin/env bash
# title					:Enhanced BASH v3
# description			:
# author				:Jessica Brown
# date					:2022-04-21
# version				:3.0.0
# usage					:
# notes					:
# bash_version	:5.1.16(1)-release
# ==============================================================================

unset eb3_BinPath
unset eb3_CachePath
unset eb3_TempPath
unset eb3_LibPath
unset eb3_ModPath
unset eb3_EtcPath
unset eb3_ConfPath
unset eb3_OptPath
unset eb3_UsrPath
unset eb3_OverRidesPath
unset eb3_ThemesPath
unset eb3_VarPath
unset eb3_LogsPath
